const assert=require('assert');const fs=require('fs');const path=require('path');const vm=require('vm');
const game=require('../cloudbase/_shared/game');
(async()=>{
// malformed/legacy numeric fields must become safe numbers before rewards mutate them
let s=game.newPlayer('corrupt');s.coin='5000';s.tickets='30';s.starCrystal='300';s.heroes.h004.fragments='10';s.formation=['h004','h004','h004'];s.inventory.equipment.eq004=1;s.heroes.h004.equipment.weapon='eq004';s.heroes.h004.equipment.armor='eq005';s.activeRelic='r004';s.inventory.relics.r004=0;s=game.migrate(s,'corrupt');
assert.equal(typeof s.coin,'number');assert.equal(typeof s.tickets,'number');assert.equal(typeof s.starCrystal,'number');assert.equal(typeof s.heroes.h004.fragments,'number');assert.deepEqual(s.formation,['h004']);assert.equal(s.heroes.h004.equipment.weapon,'eq004');assert.equal(s.heroes.h004.equipment.armor,null);assert.equal(s.activeRelic,null);
delete s.systemMailPolicy;s.mails=[];s=game.migrate(s,'corrupt-legacy');const before=s.coin;game.claimMail(s,'v08_event');assert.equal(s.coin,before+6000);assert.equal(typeof s.coin,'number','reward mutation must not concatenate numeric strings');
// over-equipped copies are repaired deterministically during migration
let gear=game.newPlayer('gear-corrupt');gear.heroes.h001={level:1,star:1,fragments:0,awakening:0,signature:null,equipment:{weapon:'eq001',armor:null,charm:null}};gear.formation=['h004','h001'];gear=game.migrate(gear);assert.equal([gear.heroes.h004.equipment.weapon,gear.heroes.h001.equipment.weapon].filter(Boolean).length,1);
// metadata must be aligned across release surfaces
const root=path.resolve(__dirname,'..'),version=JSON.parse(fs.readFileSync(path.join(root,'web/version.json'),'utf8')),pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')),html=fs.readFileSync(path.join(root,'web/index.html'),'utf8'),cocos=fs.readFileSync(path.join(root,'cocos-project/assets/scripts/release/ReleaseConfig.ts'),'utf8');assert.equal(version.version,'2.2.0');assert.equal(version.configVersion,game.CONFIG_VERSION);assert.equal(pkg.version,version.version);assert.ok(html.includes('v2.2.0'));assert.ok(cocos.includes("version:'2.2.0'")&&cocos.includes("configVersion:'2026.09.v21.5'"));
// cloud helper must not swallow transient read failures into a fresh save write
const cloudCode=fs.readFileSync(path.join(root,'cloudbase/_shared/cloud.js'),'utf8'),mod={exports:{}};vm.runInNewContext(cloudCode,{require:(id)=>id==='crypto'?require('crypto'):id==='@cloudbase/js-sdk'?{}:id==='./game'?game:require(id),module:mod,exports:mod.exports,console,Date});const helpers=mod.exports;let writes=0;const failingDb={collection:()=>({where:()=>({get:async()=>{throw new Error('DB_DOWN')}}),doc:()=>({set:async()=>{writes++}})})};await assert.rejects(()=>helpers.getOrCreate(failingDb,'player-x'),/DB_DOWN/);assert.equal(writes,0,'transient read errors must never create/overwrite a player');
// source-level guarantees for link-code CAS and client connection flow
const cloudSrc=cloudCode;assert.ok(cloudSrc.includes("findById(db,'players',key)"));assert.ok(cloudSrc.includes("where({_id:normalized,used:false}).update"));const bridge=fs.readFileSync(path.join(root,'web/cloud-bridge.js'),'utf8');assert.ok(bridge.includes('ensurePromise'));assert.ok(bridge.includes('data-star-ember-cloudbase'));const app=fs.readFileSync(path.join(root,'web/app.js'),'utf8');const redeem=app.slice(app.indexOf('async function redeemLinkCode'),app.indexOf('async function setLoadout'));assert.ok(redeem.includes('connectCloudCore()'));assert.ok(!redeem.includes('await connectCloud()'));assert.ok(redeem.includes('!G.isPristine(state)'));
console.log('v2.2.0 stability regression passed');
})().catch(e=>{console.error(e);process.exit(1)});
